name: Build diff-pdf
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'testing/<stuff>'
    branches:
      - main
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'
    # Run pipeline for release tags
    tags:
      - 'v*.*.*'

permissions:
  # Allow the release creation
  contents: write

jobs:
  build-ubuntu-22-04:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: vslavik/diff-pdf
          ref: master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq make automake g++
          sudo apt-get install -yq libpoppler-glib-dev poppler-utils libwxgtk3.0-gtk3-dev
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: ./configure
      - name: Build
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: diff-pdf
          path: diff-pdf

  # Create a release if running on tag
  create-release:
    needs: [build-ubuntu-22-04]
    runs-on: [ubuntu-24.04]
    # Only run on pushed tags (and explicitly ignore scheduled runs)
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    steps:
      - name: Collect artifacts
        uses: actions/download-artifact@v8
      - name: Release diff-pdf
        uses: softprops/action-gh-release@v3
        with:
          files: |
            diff-pdf
